# Generated by Django 6.1.1 on 2026-09-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pyq',
            options={'ordering': ['semester', '-exam_year', 'subject']},
        ),
        migrations.RemoveField(
            model_name='pyq',
            name='year',
        ),
        migrations.AddField(
            model_name='pyq',
            name='academic_year',
            field=models.CharField(default='1st Year', max_length=50),
        ),
        migrations.AddField(
            model_name='pyq',
            name='branch',
            field=models.CharField(default='Computer Science & Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='pyq',
            name='exam_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='pyq',
            name='session',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pyq',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pyq',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pyq',
            name='subject',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pyq',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
